import Kolaznik_1 from "../../assets/images/Korisnik_1.png";
import Kolaznik_2 from "../../assets/images/Korisnik_2.png";
import Kolaznik_3 from "../../assets/images/Korisnik_3.png";
import Kolaznik_4 from "../../assets/images/Korisnik_4.png";
import Kolaznik_5 from "../../assets/images/Korisnik_5.png";
import Kolaznik_6 from "../../assets/images/Korisnik_6.png";
import Email from "../../assets/images/Email.png";
import RezIsp from "../../assets/images/RezIsp.png";
import ZavrsniRad from "../../assets/images/ZavrsniRad.png";
